name: Changelog Test

#on:
#  - push

jobs:
  changelog_test:
    runs-on: ubuntu-22.04
    env:
      TAG_NAME: ${{ github.sha }}
    permissions: 
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment variables
        run: |
          echo "LAST_TAG=$(git describe --tags --abbrev=0 ${TAG_NAME}^)" >> $GITHUB_ENV

      - name: Generate Changelog
        id: changelog_gen
        uses: metcalfc/changelog-generator@v4.0.0
        with:
          myToken: ${{ github.token }}

      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: changelog.md
          write-mode: append
          contents: ${{ steps.changelog_gen.outputs.changelog }}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ github.token }}
          branch: tests
          force: true
          message: 'Changelog updated - ${LAST_TAG} added'
