name: Changelog Test

on:
  - push

jobs:
  dispatch_test:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    permissions: 
      contents: write
    steps:
      - name: Generate Changelog
        id: changelog_gen
        uses: mikepenz/release-changelog-builder-action@v4.0.0-rc03
        with:
          outputFile: changelog.md

      - name: read_output
        run: |
          echo "CHANGELOG=${{steps.changelog_gen.outputs.changelog}}" >> $GITHUB_ENV
          echo "CHN_FROM=${{steps.changelog_gen.outputs.fromTag}}" >> $GITHUB_ENV
          echo "CHN_TO=${{steps.changelog_gen.outputs.toTag}}" >> $GITHUB_ENV


  # if: startsWith(github.ref, 'refs/tags/')
