name: Changelog Test

on:
  - push

jobs:
  changelog_test:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
      TAG_NAME: ${{ github.sha }}
    permissions: 
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment variables
        run: |
          echo "LAST_TAG=$(git describe --tags --abbrev=0 ${TAG_NAME}^)" >> $GITHUB_ENV

      - name: Generate Changelog
        id: changelog_gen
        uses: metcalfc/changelog-generator@v4.0.0
        with:
          myToken: $GH_TOKEN

      - name: read_output
        run: |
          echo "CHANGELOG=${{steps.changelog_gen.outputs.changelog}}" >> $GITHUB_ENV
          echo "${{ steps.changelog_gen.outputs.changelog }}" | cat - changelog.md > temp && mv temp changelog.md
