name: Release

on:
  - push

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      issues: write 

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment variables
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "LAST_TAG=$(git describe --tags --abbrev=0 ${TAG_NAME}^)" >> $GITHUB_ENV
          echo "USER_NAME=$(git --no-pager show -s --format='%aN')" >> $GITHUB_ENV
          echo "USER_EMAIL=$(git --no-pager show -s --format='%aE')" >> $GITHUB_ENV
      
       - name: Create Issue
        run: |
          GITHUB_TOKEN=${{ github.token }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.repository }}
          TITLE='New Issue'
          BODY="Release.\n\n**Author**: ${{ github.actor }}\n**Date**: ${{ github.event.head_commit.timestamp }}"

          gh auth login --with-token <<< "${GH_TOKEN}"
          ISSUE_NUMBER=$(gh issue create --title "$TITLE" --body "$BODY" --json number --jq .number)
          gh issue label add $ISSUE_NUMBER --label "RELEASE"
