name: Issue Test

on:
  - push

jobs:
  issue-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write 

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment variables
        run: |
          echo "USER_NAME=$(git --no-pager show -s --format='%aN')" >> $GITHUB_ENV
          echo "USER_EMAIL=$(git --no-pager show -s --format='%aE')" >> $GITHUB_ENV
      
      - name: Create Issue
        run: |
          GITHUB_TOKEN=${{ github.token }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.repository }}
          TIMESTAMP=$(date +"%d-%m-%Y %H:%M")
          TITLE='Release'
          BODY="Release.<br>**Author**: ${{ github.actor }}<br>**Date**: $TIMESTAMP"

          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh issue create --title "$TITLE" --body "$BODY" --label "RELEASE"
