name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install dependencies
        run: npm install --force

      - name: Set up environment variables
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "LAST_TAG=$(git describe --abbrev=0 --tags v*)" >> $GITHUB_ENV
          echo "USER_NAME=$(git --no-pager show -s --format='%aN')" >> $GITHUB_ENV
          echo "USER_EMAIL=$(git --no-pager show -s --format='%aE')" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        run: |
          changelog=$(git log $(git describe --tags --abbrev=0 ${LAST_TAG})..HEAD --oneline)
          echo "::set-output name=CHANGELOG::$changelog"

      - name: Create release
        run: |
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "$USER_NAME"
          changelog=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)
          release_version=$RELEASE_VERSION
          release_date=$(date -u +"%d-%m-%Y")
          release_title="Release $RELEASE_VERSION"
          release_body="**Author**: @${{ github.actor }}
          **Date**: ${release_date}
          **Version**: ${TAG_NAME}

          **Changelog**:
          ${{ steps.changelog.outputs.CHANGELOG }}"
          gh release create ${TAG_NAME} -t "${release_title}" -n "${release_body}"
