name: Create Release

on:
  push:
    branches:
      - "*"
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up environment variables
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "TAG_NAME2=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "TAG_NAME3=${{  github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$new_tag" >> $GITHUB_ENV
          echo "USER_NAME=$(git --no-pager show -s --format='%aN')" >> $GITHUB_ENV
          echo "USER_EMAIL=$(git --no-pager show -s --format='%aE')" >> $GITHUB_ENV
          
      - name: Install dependencies
        run: npm install --force

      - name: Create release
        run: |
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "$USER_NAME"
          changelog=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)
          release_version=$RELEASE_VERSION
          release_date=$(date -u +"%d-%m-%Y")
          release_title="Release $RELEASE_VERSION"
          release_body="**Author**: ${{ github.actor }}
          **Date**: ${release_date}
          **Version**: $RELEASE_VERSION

          **Changelog**:
          ${changelog}"
          gh release create ${release_version} -t "${release_title}" -n "${release_body}"
